using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using MaintainIt_SP.Services;

namespace MaintainIt_SP.ItemsData
{
    public class ItemData
    {
        public List<string> ItemTypes = new List<string>();
        public List<string> GarageItemTypes = new List<string>();
        public List<string> MicroManufacturers = new List<string>();
        public List<string> OvenManufacturers = new List<string>();
        public List<string> FridgeManufacturers = new List<string>();
        public List<string> CarManufacturer = new List<string>();
        public List<string> PowerToolsManufacturers = new List<string>();
        public List<string> FridgeSchedule = new List<string>();
        public List<Reminder> Reminders = new List<Reminder>();

        public ObservableCollection<ItemInstance> itemInstances = new ObservableCollection<ItemInstance>();

        public ItemData()
        {
            SetItemTypes();
            SetManufacturers();
            CarLookup();
            SetGarageItems();

            SetSchedules();

            Reminders.Add(new Reminder
            {
                ReminderName = "Test",
                ReminderDesc = "This is a functionality test",
                ReminderDate = DateTime.Now.ToShortDateString()
            });
        }



        #region Item Dictionary

        private void SetItemTypes() 
        {
            ItemTypes.Add("Dishwasher");
            ItemTypes.Add("Microwave");
            ItemTypes.Add("Oven");
            ItemTypes.Add("Refrigerator");
            ItemTypes.Add("Television");
            ItemTypes.Add("Toaster");
        }

        private void SetGarageItems() 
        {
            GarageItemTypes.Add("Bicycles");
            GarageItemTypes.Add("Grill");
            GarageItemTypes.Add("Lawn Mowers");
            GarageItemTypes.Add("Outdoor Tools");
            GarageItemTypes.Add("Power Tools");
            GarageItemTypes.Add("Washer & Dryer");
        }

        private void SetManufacturers() 
        {
            MicroManufacturers.Add("Amana");
            MicroManufacturers.Add("Ariston");
            MicroManufacturers.Add("Avanti");
            MicroManufacturers.Add("Black & Decker");
            MicroManufacturers.Add("Bosch");
            MicroManufacturers.Add("Cuisinart");
            MicroManufacturers.Add("Dacor");
            MicroManufacturers.Add("Daewoo");
            MicroManufacturers.Add("Electrolux");
            MicroManufacturers.Add("Elite Lighting");
            MicroManufacturers.Add("Franke");
            MicroManufacturers.Add("Frigidaire");
            MicroManufacturers.Add("GE");
            MicroManufacturers.Add("Kenmore");
            MicroManufacturers.Add("KitchenAid");
            MicroManufacturers.Add("LG");
            MicroManufacturers.Add("Magic Chef");
            MicroManufacturers.Add("Maytag");
            MicroManufacturers.Add("Midea");
            MicroManufacturers.Add("Miele");
            MicroManufacturers.Add("Oster");
            MicroManufacturers.Add("Panasonic");
            MicroManufacturers.Add("Samsung");
            MicroManufacturers.Add("Sharp");
            MicroManufacturers.Add("Viking");
            MicroManufacturers.Add("Whirlpool");
            MicroManufacturers.Add("White-Westinghouse");
            MicroManufacturers.Add("Zanussi");

            OvenManufacturers.Add("Advance Tabco");
            OvenManufacturers.Add("AEG-Electrolux");
            OvenManufacturers.Add("Alto Shaam");
            OvenManufacturers.Add("American Range");
            OvenManufacturers.Add("APW Wyott");
            OvenManufacturers.Add("Ariston");
            OvenManufacturers.Add("Bakers Pride");
            OvenManufacturers.Add("Beko");
            OvenManufacturers.Add("Bertazzoni");
            OvenManufacturers.Add("Black & Decker");
            OvenManufacturers.Add("Blodgett");
            OvenManufacturers.Add("Bosch");
            OvenManufacturers.Add("Breville");
            OvenManufacturers.Add("Cadco");
            OvenManufacturers.Add("Cambro");
            OvenManufacturers.Add("Capital Cooking Equipment");
            OvenManufacturers.Add("Carter-Hoffman");
            OvenManufacturers.Add("Columbus McKinnon");
            OvenManufacturers.Add("Cuisinart");
            OvenManufacturers.Add("Dacor");
            OvenManufacturers.Add("Daewoo");
            OvenManufacturers.Add("DCS");
            OvenManufacturers.Add("DeLonghi");
            OvenManufacturers.Add("Dualit");
            OvenManufacturers.Add("Electrolux");
            OvenManufacturers.Add("Elite Lighting");
            OvenManufacturers.Add("Fagor");
            OvenManufacturers.Add("Fisher & Paykel");
            OvenManufacturers.Add("Franke");
            OvenManufacturers.Add("Frigidaire");
            OvenManufacturers.Add("GE");
            OvenManufacturers.Add("glem gas");
            OvenManufacturers.Add("Gorenje");
            OvenManufacturers.Add("Hamilton Beach");
            OvenManufacturers.Add("Hatco");
            OvenManufacturers.Add("Heartland");
            OvenManufacturers.Add("Hobart");
            OvenManufacturers.Add("Hotpoint");
            OvenManufacturers.Add("Indesit Co.");
            OvenManufacturers.Add("Kenmore");
            OvenManufacturers.Add("KitchenAid");
            OvenManufacturers.Add("La Germania");
            OvenManufacturers.Add("LG");
            OvenManufacturers.Add("Lofra");
            OvenManufacturers.Add("Maytag");
            OvenManufacturers.Add("Metro Foodservice");
            OvenManufacturers.Add("Miele");
            OvenManufacturers.Add("Neff GmbH");
            OvenManufacturers.Add("NESCO");
            OvenManufacturers.Add("Oster");
            OvenManufacturers.Add("Proctor Silex");
            OvenManufacturers.Add("Ronco");
            OvenManufacturers.Add("Simfer");
            OvenManufacturers.Add("Smeg");
            OvenManufacturers.Add("Southbend/Hussman");
            OvenManufacturers.Add("Star Manufacturing");
            OvenManufacturers.Add("Summit Appliance");
            OvenManufacturers.Add("Sunbeam");
            OvenManufacturers.Add("Sunpentown");
            OvenManufacturers.Add("tecnogas");
            OvenManufacturers.Add("The Hoover Company");
            OvenManufacturers.Add("Thermador");
            OvenManufacturers.Add("Toastmaster");
            OvenManufacturers.Add("Traulsen");
            OvenManufacturers.Add("True Refrigeration");
            OvenManufacturers.Add("Turbo Chef");
            OvenManufacturers.Add("Verona");
            OvenManufacturers.Add("Viking");
            OvenManufacturers.Add("Vollrath");
            OvenManufacturers.Add("Vulcan Equipment");
            OvenManufacturers.Add("Waring");
            OvenManufacturers.Add("Wells");
            OvenManufacturers.Add("Westbend");
            OvenManufacturers.Add("Whirlpool");
            OvenManufacturers.Add("Zanussi");

            FridgeManufacturers.Add("Amana");
            FridgeManufacturers.Add("Beko");
            FridgeManufacturers.Add("Bosch");
            FridgeManufacturers.Add("ElectroLux");
            FridgeManufacturers.Add("Frigidaire");
            FridgeManufacturers.Add("GE");
            FridgeManufacturers.Add("Haier");
            FridgeManufacturers.Add("Hitachi");
            FridgeManufacturers.Add("Kelvinator");
            FridgeManufacturers.Add("Kenmore");
            FridgeManufacturers.Add("KitchenAid");
            FridgeManufacturers.Add("LG");
            FridgeManufacturers.Add("Liebherr");
            FridgeManufacturers.Add("MayTag");
            FridgeManufacturers.Add("Miele");
            FridgeManufacturers.Add("Panasonic");
            FridgeManufacturers.Add("Samsung");
            FridgeManufacturers.Add("Sharp");
            FridgeManufacturers.Add("Sub-Zero");
            FridgeManufacturers.Add("Viking");
            FridgeManufacturers.Add("Walton");
            FridgeManufacturers.Add("Whirlpool");

            PowerToolsManufacturers.Add("Milwaukee");
            PowerToolsManufacturers.Add("DeWalt");
            PowerToolsManufacturers.Add("Makita");
            PowerToolsManufacturers.Add("Bosch");
            PowerToolsManufacturers.Add("Stihl");
            PowerToolsManufacturers.Add("Rigid");
            PowerToolsManufacturers.Add("Stanley, Inc.");
            PowerToolsManufacturers.Add("Irwin");
            PowerToolsManufacturers.Add("Porter Cable");
            PowerToolsManufacturers.Add("Ryobi");
            PowerToolsManufacturers.Add("Dremel");
            PowerToolsManufacturers.Add("Carhartt");
            PowerToolsManufacturers.Add("Festool");
            PowerToolsManufacturers.Add("3M");
            PowerToolsManufacturers.Add("Channel Lock");
            PowerToolsManufacturers.Add("Bostitch");
            PowerToolsManufacturers.Add("Estwing");
            PowerToolsManufacturers.Add("Metabo");
            PowerToolsManufacturers.Add("Lenox");
            PowerToolsManufacturers.Add("Kreg");
            PowerToolsManufacturers.Add("Fein");
            PowerToolsManufacturers.Add("Delta");
            PowerToolsManufacturers.Add("Kobalt");
            PowerToolsManufacturers.Add("Black & Decker");
            PowerToolsManufacturers.Add("Stabila");
            PowerToolsManufacturers.Add("Fiskars");
            PowerToolsManufacturers.Add("Skil");
            PowerToolsManufacturers.Add("Jet");
            PowerToolsManufacturers.Add("Werner");
            PowerToolsManufacturers.Add("Rubbermaid");
            PowerToolsManufacturers.Add("Elmer's Products");
            PowerToolsManufacturers.Add("Generac");
            PowerToolsManufacturers.Add("Emerson");
        }

        #endregion

        #region Car Dictionary 
        private void CarLookup()
        {
            CarManufacturer.Add("Škoda");
            CarManufacturer.Add("Abadal");
            CarManufacturer.Add("Abarth");
            CarManufacturer.Add("Abbott-Detroit");
            CarManufacturer.Add("ABT");
            CarManufacturer.Add("AC Cars");
            CarManufacturer.Add("Acura");
            CarManufacturer.Add("Aixam");
            CarManufacturer.Add("Alfa Romeo");
            CarManufacturer.Add("Alpina");
            CarManufacturer.Add("Alpine");
            CarManufacturer.Add("Alta");
            CarManufacturer.Add("Alvis");
            CarManufacturer.Add("AMC");
            CarManufacturer.Add("Apollo");
            CarManufacturer.Add("Arash");
            CarManufacturer.Add("Ariel");
            CarManufacturer.Add("ARO");
            CarManufacturer.Add("Arrinera");
            CarManufacturer.Add("Artega");
            CarManufacturer.Add("Ascari");
            CarManufacturer.Add("Askam");
            CarManufacturer.Add("Aston Martin");
            CarManufacturer.Add("Atalanta");
            CarManufacturer.Add("Auburn");
            CarManufacturer.Add("Audi");
            CarManufacturer.Add("Austin");
            CarManufacturer.Add("Autobacs");
            CarManufacturer.Add("Autobianchi");
            CarManufacturer.Add("Axon");
            CarManufacturer.Add("BAC");
            CarManufacturer.Add("BAIC Motor");
            CarManufacturer.Add("Baojun");
            CarManufacturer.Add("Bentley");
            CarManufacturer.Add("Berkeley");
            CarManufacturer.Add("Berliet");
            CarManufacturer.Add("Bertone");
            CarManufacturer.Add("BharatBenz");
            CarManufacturer.Add("Bitter");
            CarManufacturer.Add("Bizzarrini");
            CarManufacturer.Add("BMW");
            CarManufacturer.Add("Borgward");
            CarManufacturer.Add("Bowler");
            CarManufacturer.Add("Brabus");
            CarManufacturer.Add("Brammo");
            CarManufacturer.Add("Brilliance");
            CarManufacturer.Add("Bristol");
            CarManufacturer.Add("Brooke");
            CarManufacturer.Add("Bufori");
            CarManufacturer.Add("Bugatti");
            CarManufacturer.Add("Buick");
            CarManufacturer.Add("BYD");
            CarManufacturer.Add("Cadillac");
            CarManufacturer.Add("Caparo");
            CarManufacturer.Add("Carlsson");
            CarManufacturer.Add("Caterham");
            CarManufacturer.Add("Changan");
            CarManufacturer.Add("Changfeng");
            CarManufacturer.Add("Chery");
            CarManufacturer.Add("Chevrolet");
            CarManufacturer.Add("Chrysler");
            CarManufacturer.Add("Cisitalia");
            CarManufacturer.Add("Citroën");
            CarManufacturer.Add("Cizeta");
            CarManufacturer.Add("Cole");
            CarManufacturer.Add("Corre La Licorne");
            CarManufacturer.Add("Corvette");
            CarManufacturer.Add("Dacia");
            CarManufacturer.Add("Daewoo");
            CarManufacturer.Add("DAF");
            CarManufacturer.Add("Daihatsu");
            CarManufacturer.Add("Daimler");
            CarManufacturer.Add("Dartz");
            CarManufacturer.Add("Datsun");
            CarManufacturer.Add("David Brown");
            CarManufacturer.Add("De Tomaso");
            CarManufacturer.Add("Delage");
            CarManufacturer.Add("Detroit Electric");
            CarManufacturer.Add("Devel Sixteen");
            CarManufacturer.Add("Diatto");
            CarManufacturer.Add("DINA");
            CarManufacturer.Add("DKW");
            CarManufacturer.Add("DMC");
            CarManufacturer.Add("Dodge");
            CarManufacturer.Add("Dongfeng");
            CarManufacturer.Add("Donkervoort");
            CarManufacturer.Add("DS");
            CarManufacturer.Add("Eagle");
            CarManufacturer.Add("EDAG");
            CarManufacturer.Add("Edsel");
            CarManufacturer.Add("Eicher");
            CarManufacturer.Add("Elemental");
            CarManufacturer.Add("Elfin");
            CarManufacturer.Add("Elva");
            CarManufacturer.Add("Englon");
            CarManufacturer.Add("ERF");
            CarManufacturer.Add("Eterniti");
            CarManufacturer.Add("Facel Vega");
            CarManufacturer.Add("Faraday Future");
            CarManufacturer.Add("FAW");
            CarManufacturer.Add("Ferrari");
            CarManufacturer.Add("Fiat");
            CarManufacturer.Add("Fioravanti");
            CarManufacturer.Add("Fisker");
            CarManufacturer.Add("Foden");
            CarManufacturer.Add("Force Motors");
            CarManufacturer.Add("Ford");
            CarManufacturer.Add("Foton");
            CarManufacturer.Add("FPV");
            CarManufacturer.Add("Franklin");
            CarManufacturer.Add("Freightliner");
            CarManufacturer.Add("GAC Group");
            CarManufacturer.Add("Gardner Douglas");
            CarManufacturer.Add("GAZ");
            CarManufacturer.Add("Geely");
            CarManufacturer.Add("General Motors");
            CarManufacturer.Add("Genesis");
            CarManufacturer.Add("Geo");
            CarManufacturer.Add("Gilbern");
            CarManufacturer.Add("Gillet");
            CarManufacturer.Add("Ginetta");
            CarManufacturer.Add("GMC");
            CarManufacturer.Add("Gonow");
            CarManufacturer.Add("Great Wall");
            CarManufacturer.Add("Grinnall");
            CarManufacturer.Add("GT-R");
            CarManufacturer.Add("GTA Motor");
            CarManufacturer.Add("Gumpert");
            CarManufacturer.Add("Hafei");
            CarManufacturer.Add("Haima");
            CarManufacturer.Add("Haval");
            CarManufacturer.Add("Hawtai");
            CarManufacturer.Add("Hennessey");
            CarManufacturer.Add("Hillman");
            CarManufacturer.Add("Hindustan Motors");
            CarManufacturer.Add("Hino");
            CarManufacturer.Add("Hispano-Suiza");
            CarManufacturer.Add("Holden");
            CarManufacturer.Add("Hommell");
            CarManufacturer.Add("Honda");
            CarManufacturer.Add("Horch");
            CarManufacturer.Add("HSV");
            CarManufacturer.Add("Hudson");
            CarManufacturer.Add("Hummer");
            CarManufacturer.Add("Hupmobile");
            CarManufacturer.Add("Hyundai");
            CarManufacturer.Add("IC Bus");
            CarManufacturer.Add("IH");
            CarManufacturer.Add("IKCO");
            CarManufacturer.Add("Infiniti");
            CarManufacturer.Add("Innocenti");
            CarManufacturer.Add("Intermeccanica");
            CarManufacturer.Add("International");
            CarManufacturer.Add("Irizar");
            CarManufacturer.Add("Isdera");
            CarManufacturer.Add("Iso Rivolta");
            CarManufacturer.Add("Isuzu");
            CarManufacturer.Add("Iveco");
            CarManufacturer.Add("JAC Motors");
            CarManufacturer.Add("Jaguar");
            CarManufacturer.Add("Jawa");
            CarManufacturer.Add("JBA Motors");
            CarManufacturer.Add("Jeep");
            CarManufacturer.Add("Jensen");
            CarManufacturer.Add("JMC");
            CarManufacturer.Add("Kaiser");
            CarManufacturer.Add("Kamaz");
            CarManufacturer.Add("Karma");
            CarManufacturer.Add("Keating");
            CarManufacturer.Add("Kenworth");
            CarManufacturer.Add("KIA");
            CarManufacturer.Add("Koenigsegg");
            CarManufacturer.Add("KTM");
            CarManufacturer.Add("Lada");
            CarManufacturer.Add("Lagonda");
            CarManufacturer.Add("Lamborghini");
            CarManufacturer.Add("Lancia");
            CarManufacturer.Add("Land Rover");
            CarManufacturer.Add("Landwind");
            CarManufacturer.Add("Laraki");
            CarManufacturer.Add("LEVC");
            CarManufacturer.Add("Lexus");
            CarManufacturer.Add("Leyland");
            CarManufacturer.Add("Lifan");
            CarManufacturer.Add("Ligier");
            CarManufacturer.Add("Lincoln");
            CarManufacturer.Add("Lister");
            CarManufacturer.Add("Lloyd");
            CarManufacturer.Add("Lobini");
            CarManufacturer.Add("Lotus");
            CarManufacturer.Add("Lucid");
            CarManufacturer.Add("Luxgen");
            CarManufacturer.Add("M BMW");
            CarManufacturer.Add("Mack");
            CarManufacturer.Add("Mahindra");
            CarManufacturer.Add("MAN");
            CarManufacturer.Add("Mansory");
            CarManufacturer.Add("Marcos");
            CarManufacturer.Add("Marlin");
            CarManufacturer.Add("Maserati");
            CarManufacturer.Add("Mastretta");
            CarManufacturer.Add("Maxus");
            CarManufacturer.Add("Maybach");
            CarManufacturer.Add("MAZ");
            CarManufacturer.Add("Mazda");
            CarManufacturer.Add("Mazzanti");
            CarManufacturer.Add("McLaren");
            CarManufacturer.Add("Melkus");
            CarManufacturer.Add("Mercedes-Benz");
            CarManufacturer.Add("Mercury");
            CarManufacturer.Add("Merkur");
            CarManufacturer.Add("MEV");
            CarManufacturer.Add("MG");
            CarManufacturer.Add("Microcar");
            CarManufacturer.Add("Mini");
            CarManufacturer.Add("Mitsubishi");
            CarManufacturer.Add("Mitsuoka");
            CarManufacturer.Add("MK");
            CarManufacturer.Add("Morgan");
            CarManufacturer.Add("Morris");
            CarManufacturer.Add("Mosler");
            CarManufacturer.Add("Mustang");
            CarManufacturer.Add("Navistar");
            CarManufacturer.Add("Nismo");
            CarManufacturer.Add("Nissan");
            CarManufacturer.Add("Noble");
            CarManufacturer.Add("Oldsmobile");
            CarManufacturer.Add("Oltcit");
            CarManufacturer.Add("Opel");
            CarManufacturer.Add("OSCA");
            CarManufacturer.Add("Paccar");
            CarManufacturer.Add("Pagani");
            CarManufacturer.Add("Panhard");
            CarManufacturer.Add("Pegaso");
            CarManufacturer.Add("Perodua");
            CarManufacturer.Add("Peterbilt");
            CarManufacturer.Add("Peugeot");
            CarManufacturer.Add("PGO");
            CarManufacturer.Add("Pierce-Arrow");
            CarManufacturer.Add("Pininfarina");
            CarManufacturer.Add("Plymouth");
            CarManufacturer.Add("Polestar");
            CarManufacturer.Add("Pontiac");
            CarManufacturer.Add("Porsche");
            CarManufacturer.Add("Praga");
            CarManufacturer.Add("Premier");
            CarManufacturer.Add("Prodrive");
            CarManufacturer.Add("Proton");
            CarManufacturer.Add("Qoros");
            CarManufacturer.Add("Radical");
            CarManufacturer.Add("RAM");
            CarManufacturer.Add("Rambler");
            CarManufacturer.Add("Ranz");
            CarManufacturer.Add("Renault");
            CarManufacturer.Add("Renault Samsung");
            CarManufacturer.Add("Rezvani");
            CarManufacturer.Add("Riley");
            CarManufacturer.Add("Rimac");
            CarManufacturer.Add("Rinspeed");
            CarManufacturer.Add("Roewe");
            CarManufacturer.Add("Rolls-Royce");
            CarManufacturer.Add("Ronart");
            CarManufacturer.Add("Rossion");
            CarManufacturer.Add("Rover");
            CarManufacturer.Add("RUF");
            CarManufacturer.Add("Saab");
            CarManufacturer.Add("SAIC");
            CarManufacturer.Add("Saipa");
            CarManufacturer.Add("Saleen");
            CarManufacturer.Add("Saturn");
            CarManufacturer.Add("Scion");
            CarManufacturer.Add("SEAT");
            CarManufacturer.Add("Setra");
            CarManufacturer.Add("Shelby");
            CarManufacturer.Add("Simca");
            CarManufacturer.Add("Singer");
            CarManufacturer.Add("Sisu Auto");
            CarManufacturer.Add("Smart");
            CarManufacturer.Add("Soueast");
            CarManufacturer.Add("Spirra");
            CarManufacturer.Add("Spyker");
            CarManufacturer.Add("SRT");
            CarManufacturer.Add("SsangYong");
            CarManufacturer.Add("SSC");
            CarManufacturer.Add("Sterling");
            CarManufacturer.Add("Studebaker");
            CarManufacturer.Add("Subaru");
            CarManufacturer.Add("Suffolk");
            CarManufacturer.Add("Suzuki");
            CarManufacturer.Add("Talbot");
            CarManufacturer.Add("Tata");
            CarManufacturer.Add("Tatra");
            CarManufacturer.Add("Tauro Sport Auto");
            CarManufacturer.Add("TechArt");
            CarManufacturer.Add("Tesla");
            CarManufacturer.Add("Toyota");
            CarManufacturer.Add("Toyota Crown");
            CarManufacturer.Add("Tramontana");
            CarManufacturer.Add("Trion");
            CarManufacturer.Add("Triumph");
            CarManufacturer.Add("Troller");
            CarManufacturer.Add("TVR");
            CarManufacturer.Add("UAZ");
            CarManufacturer.Add("UD");
            CarManufacturer.Add("Ultima");
            CarManufacturer.Add("Vandenbrink");
            CarManufacturer.Add("Vauxhall");
            CarManufacturer.Add("Vector Motors");
            CarManufacturer.Add("Vencer");
            CarManufacturer.Add("Venturi");
            CarManufacturer.Add("Venucia");
            CarManufacturer.Add("Viper");
            CarManufacturer.Add("Volkswagen");
            CarManufacturer.Add("Volvo");
            CarManufacturer.Add("W Motors");
            CarManufacturer.Add("Wanderer");
            CarManufacturer.Add("Wartburg");
            CarManufacturer.Add("Western Star");
            CarManufacturer.Add("Westfield");
            CarManufacturer.Add("Wiesmann");
            CarManufacturer.Add("Willys");
            CarManufacturer.Add("Wuling");
            CarManufacturer.Add("Yulon");
            CarManufacturer.Add("Zastava");
            CarManufacturer.Add("ZAZ");
            CarManufacturer.Add("Zenos");
            CarManufacturer.Add("Zenvo");
            CarManufacturer.Add("Zotye");
        }
        #endregion

        private void SetSchedules()
        {
            FridgeSchedule.Add("Clean condenser coils.");
            FridgeSchedule.Add("Clean door seals.");
        }

    }
}
